# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vinyla' do
   pod 'RxSwift', '6.2.0'
   pod 'RxCocoa', '6.2.0' 
   pod 'Cosmos', '~> 23.0'

 # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vinyla

  target 'VinylaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
